- name: "Remove nginx default conf"
  become: yes
  file: "path=/etc/nginx/{{item}} state=absent"
  with_items:
    - sites-available/default
    - sites-enabled/default

- name: "Copy nginx configuration for wordpress"
  become: yes
  template: src=nginx.conf dest=/etc/nginx/sites-available/wordpress
  notify: restart nginx

- name: "Create symlink between sites-available and sites-enabled"
  become: yes
  file: src=/etc/nginx/sites-available/wordpress dest=/etc/nginx/sites-enabled/wordpress state=link

- name: "Create directory for the unix socket"
  become: yes
  file: path=/var/run/php7-fpm/ recurse=yes state=directory owner=www-data group=www-data

- name: "Check if the unix sock exists"
  stat: path=/var/run/php7-fpm/wordpress.sock
  register: php_sock

- name: "Touch the unix sock"
  become: yes
  file: path=/var/run/php7-fpm/wordpress.sock state=touch owner=www-data group=www-data
  notify: restart nginx
  when: not php_sock.stat.exists

- name: "Disable php7-fpm default config"
  become: yes
  command: mv /etc/php/7.0/fpm/pool.d/www.conf /etc/php/7.0/fpm/pool.d/www.disabled creates=/etc/php/7.0/fpm/pool.d/www.disabled

- name: "Copy php7-fpm configuration"
  become: yes
  template: src=php7-fpm.conf dest=/etc/php/7.0/fpm/pool.d/wordpress.conf
  notify: restart php7.0-fpm
