---
- name: "Install Nginx, php7-fpm, Mysql and php7-mysql"
  sudo: yes
  apt: "pkg={{item}} state=latest update_cache=true"
  with_items:
    - nginx
    - php7.0-fpm
    - php7.0-gd
    - mysql-server
    - php7.0-mysql
    - python-mysqldb
