---
- name: "Download wordpress"
  sudo: yes
  get_url: "url={{ storyteller_wp_file_url }}/{{ storyteller_wp_file }} dest=/srv/{{ storyteller_wp_file }} sha256sum='{{ storyteller_wp_sha256sum }}'"

- name: "Extract archive"
  sudo: yes
  unarchive: "src=/srv/{{ storyteller_wp_file }} dest=/srv copy=no creates=/srv/wordpress"

- name: "Detect if there is a wp-config file"
  sudo: yes
  stat: path=/srv/wordpress/wp-config.php
  register: wp_config

- name: "Fetch salts for wordpress config"
  command: curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  when: not wp_config.stat.exists

- name: "Copy Wordpress config"
  sudo: yes
  template: src=wp-config.php dest=/srv/wordpress/
  when: not wp_config.stat.exists

- name: "Create group wordpress"
  sudo: yes
  group: name=wordpress

- name: "Create user wordpress"
  sudo: yes
  user: name=wordpress group=wordpress home=/srv/wordpress/

- name: "Change ownership of Wordpress installation"
  sudo: yes
  file: path=/srv/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes
